### ISSUE TITLE
Plugin repository

### ISSUE THREAD

**Issue by jamtur01** [danger/danger-plugin-template#2]
The docs mention:

```
Create a Pull Request to add your plugin to the list of known plugins in https://github.com/danger/danger_plugins/blob/master/plugins.json
```

That repo does not exist. :(

**Comment by orta** [comment]
Thanks updated! https://github.com/danger/danger-plugin-template/commit/de14f28b37e74376b439129f30abc2c50ac47712

( note `danger plugin lint` doesn't actually _lint_ yet, but if you've copied the rdoc syntax from danger-prose then it should be cool, it's my last blocker around letting other plugins in - https://github.com/danger/danger/issues/313
