### ISSUE TITLE
Missing gems for run tests on plugin

### ISSUE THREAD

**Issue by diogot** [danger/danger-plugin-template#4]
I'm not a ruby expert so this might be wrong, but I'm doing a [plugin](https://github.com/diogot/danger-xcode_summary) based on this template and got some issues to run `bundle exec rake spec` and `bundle exec guard` as stated on `README.md`.
In order to work I had to add this gems for my `Gemfile`:

```
gem 'danger'
gem 'yard'
gem 'rubocop'
```

Let me know If this is the correct fix so I can do a PR fixing it :-)

**Comment by dbgrandi** [comment]
Thanks for opening this! I've fixed it in https://github.com/danger/danger-plugin-template/pull/6 by adding those to the `.gemspec` file so they are included as dependencies for anybody installing it after you publish your plugin.
