### ISSUE TITLE
How to access github object inside pluging

### ISSUE THREAD

**Issue by diogot** [danger/danger-plugin-template#5]
I'm not a ruby expert so this might be obvious, but I'm doing a [plugin](https://github.com/diogot/danger-xcode_summary) based on this template and I got some issues in accessing `github` object, I need `head_commit`, I tried [this](https://github.com/diogot/danger-xcode_summary/blob/master/lib/xcode_summary/plugin.rb#L70):

```
commit = github.head_commit
```

But didn't failed, what is the right way to do it?

**Comment by orta** [comment]
That's how you access it, could it be running against an older version of Danger ( e.g. before we updated to supporting `github.thing`? )

For example in [danger-prose we use](https://github.com/dbgrandi/danger-prose/blob/master/lib/danger_plugin.rb#L73) `github.branch_for_head`

**Comment by diogot** [comment]
Just figured out, it was my bad!
I was running tests and didn't mocked anything, just learning ruby, hehe.

Thanks!
