### ISSUE TITLE
Simplify spec_helper regarding danger_ui?

### ISSUE THREAD

**Issue by dblock** [danger/danger-plugin-template#8]
What's the reason for all of https://github.com/danger/danger-plugin-template/blob/master/spec/spec_helper.rb#L29?

Can I just do the following and should it be changed here?

```ruby
def testing_ui
  Cork::Board.new(silent: true)
end
```

**Comment by orta** [comment]
You can, but you don't get the de-colourizing, and ensure that you get consistent line breaks among different test runners

**Comment by orta** [comment]
so you have less determinate tests, and harder to test strings
